apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:9912ccbf8d22bbafbf971124600fbb0b13b9cbd6
    args: ["--dockerfile=/workspace/Dockerfile",
            "--context=dir://workspace",
            "--cache=true",
            "--cache-repo=siddhardhan/kaniko-example-cache",
            "--destination=siddhardhan/kaniko-example"] # replace with your dockerhub account
    volumeMounts:
      - name: dockerhub-secret
        mountPath: /root
      - name: dockerwsfile-volume
        mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: dockerhub-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: .docker/config.json
    - name: dockerwsfile-volume
      configMap:
        name: dockerwsfile